---
title: "Joins"
author: "Desik Somasundaram"
date: "8/17/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(palmerpenguins)
```

## Refresher 1

```{r}
penguins_subset <- penguins %>%
  filter(island %in% c("Biscoe", "Dream")) %>%
  select(!sex, !year) %>% 
  mutate(body_mass_kg = body_mass_g / 1000) %>% 
  rename(location = island)
  
```

## Refresher 2

```{r}
penguins_subset2 <- penguins %>% 
  filter(species == "Adelie") %>% 
  filter(!is.na(flipper_length_mm)) %>% 
  group_by(sex) %>% 
  summarize(mean = mean(flipper_length_mm), 
            sd = sd(flipper_length_mm),
            n = n())
```

## Joins practice

```{r}
animals <- tibble::tribble(
  ~location,   ~species,  ~maturity,
   "lagoon",   "bobcat",    "adult",
    "bluff",   "coyote", "juvenile",
    "creek",      "fox",    "adult",
     "oaks", "squirrel", "juvenile",
    "bluff",   "bobcat",    "adult"
  )

sites <- tibble::tribble(
           ~location,      ~full_site_name, ~jurisdiction,
             "beach",       "Goleta Beach",     "SB City",
            "lagoon",        "UCSB Lagoon",        "UCSB",
             "bluff",       "Ellwood Mesa",     "SB City",
              "oaks", "Fremont Campground",        "USFS"
           )

```

### Full join

```{r}
animals_fulljoin <- full_join(animals, sites)

```
### Left join

```{r}
animals_leftjoin <- left_join(animals, sites)
```
### Inner join

```{r}
animals_innerjoin <- inner_join(animals, sites)
```

## Filtering joins

```{r}
animals_semijoin <- semi_join(animals, sites, by = "location")
```


## Anti join

```{r}
animals_antijoin <- anti_join(animals, sites)
```

